# wrangler.toml
name = 'bitcoin-monitor-x-auto'
main = "src/worker.js"
compatibility_date = "2025-09-08"


# 可选：定时任务（例如每天 10:00 UTC 触发，你可在 CRON 里调用 /tweet）
[triggers]
crons = ["0 10 * * *"]


[[kv_namespaces]]
binding = "TWITTER_KV"
id = ""
preview_id = ""

[[kv_namespaces]]
binding = "btcrank"
id = ""
preview_id = ""

[vars]
CLIENT_ID = ""
CLIENT_SECRET = ""
REDIRECT_URI = "https://bitcoin-monitor-x-auto.feng73440.workers.dev/auth/callback"
SCOPES = "tweet.write tweet.read offline.access"
